services:
  local-db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: local-root
    ports:
      - 3307:3306
  dev-db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dev-root
    ports:
      - 3308:3306
  prod-db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: prod-root
    ports:
      - 3309:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - 9025:25
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-4-management 
    ports:
      - 5672:5672
      - 15672:15672
  
  
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2182:2181
  
  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper-1

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  